- hosts: all
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_port_test.yml

- hosts: all
  become: yes

  roles:
    - role: system

    - role: docker

    - role: services

    - role: geerlingguy.security
