---
- name: Copy ansible-nas install script
  copy:
    src: install.sh
    dest: /home/{{ username }}/install.sh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x

#if repo exists, delete it and clone it again
- name: Delete ansible-nas repo
  file:
    path: /home/{{ username }}/ansible-nas
    state: absent

- name: Clone ansible-nas repo
  git:
    repo: https://github.com/davestephens/ansible-nas.git
    dest: /home/{{ username }}/ansible-nas
    clone: yes

- name: Copy expect script
  copy:
    src: expect_script.exp
    dest: /home/{{ username }}/ansible-nas/
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: a+x

- name: Copy sample inventory
  command: sudo cp -rfp inventories/sample inventories/my-ansible-nas
  args:
    chdir: /home/{{ username }}/ansible-nas

- name: Echo services
  shell: echo {{ item }} >> /home/{{ username }}/ansible-nas/inventories/my-ansible-nas/group_vars/nas.yml
  loop: "{{ services }}"

- name: Run install.sh
  command: sudo sh /home/{{ username }}/install.sh {{username}}
  register: shell_result

- name: Run expect script
  expect:
    chdir: /home/{{ username }}/ansible-nas
    command: sudo ./expect_script.exp {{ secret_password | password_hash('sha512') }}
    responses: "{{ secret_password | password_hash('sha512') }}"
    timeout: 1000

- name: Clean up
  file:
    path: /home/{{ username }}/install.sh
    state: absent
  file:
    path: /home/{{ username }}/ansible-nas
    state: absent
