---
- name: Create authelia config directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/authelia/config"
    state: directory
    mode: "0755"
    access_time: preserve
    modification_time: preserve

- name: Create authelia config file
  ansible.builtin.template:
    src: authelia_config.yml.j2
    dest: "{{ docker_dir }}/authelia/config/configuration.yml"
    mode: "0644"
    owner: "{{ username }}"
    group: "{{ username }}"
  changed_when: false

- name: Create authelia users database file
  ansible.builtin.copy:
    content: |
      ---
      users:
        admin:
          displayname: admin
          email: "{{ authelia_admin_mail }}"
          password: "{{ authelia_admin_argon2id_pass }}"
          groups:
            - admins
            - dev
      ...
    dest: "{{ docker_dir }}/authelia/config/users_database.yml"
    mode: "0644"
    owner: "{{ username }}"
    group: "{{ username }}"
  changed_when: false

- name: Create authelia container
  community.docker.docker_container:
    name: authelia
    image: authelia/authelia:latest
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ docker_dir }}/authelia/config:/config"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.authelia.rule: "Host(`auth.{{ domain }}`)"
      traefik.http.routers.authelia.entrypoints: "https"
      traefik.http.routers.authelia.tls: "true"
      traefik.http.middlewares.authelia.forwardAuth.address: "http://authelia:9091/api/verify?rd=https://auth.{{ domain }}"
      traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: "true"
      traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: "Remote-User, Remote-Groups, Remote-Name, Remote-Email"
    exposed_ports:
      - "9091"
    env:
      TZ: "{{ timezone }}"
