---
- name: Add required permissions to data directories
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ data_dir }}"

- name: Add required permissions to docker_apps directories
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - {{ service_list }}

# the above makes acme.json too permissive again we should set other specific perms here
- name: Fix specific perms
  ansible.builtin.file:
    path: "{{ docker_dir }}/traefik/data/acme.json"
    state: file
    mode: "0600"

- name: Reboot the server
  ansible.builtin.reboot:
    msg: "Rebooting server to finish setup"

- name: Check if traefik is working properly with authelia middleware
  ansible.builtin.uri:
    url: "https://wg.{{ domain }}"
  ignore_errors: true
  register: traefik_authelia_check

- name: Wait to ensure authelia is up and running
  ansible.builtin.wait_for:
    timeout: 10
  when: traefik_authelia_check.status != 200

- name: Restart traefik container to ensure it can find authelia middleware
  community.docker.docker_container:
    name: traefik
    state: started
    restart: true
    timeout: 300
  when: traefik_authelia_check.status != 200
