---
- name: Create n8n container
  community.docker.docker_container:
    name: n8n
    image: docker.n8n.io/n8nio/n8n
    state: started
    restart_policy: unless-stopped
    pull: true
    volumes:
      - "{{ docker_dir }}/n8n:/home/node/.n8n"
    networks:
      - name: homelab
    env:
      GENERIC_TIMEZONE: "{{ timezone }}"
      TZ: "{{ timezone }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.n8n.entrypoints: "http"
      traefik.http.routers.n8n.rule: "Host(`n8n.{{ domain }}`)"
      traefik.http.middlewares.n8n-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.n8n.middlewares: "n8n-https-redirect"
      traefik.http.routers.n8n-secure.entrypoints: "https"
      traefik.http.routers.n8n-secure.rule: "Host(`n8n.{{ domain }}`)"
      traefik.http.routers.n8n-secure.tls: "true"
      traefik.http.routers.n8n-secure.service: "n8n"
      traefik.http.routers.n8n-secure.middlewares: "authelia@docker"
      traefik.http.services.n8n.loadbalancer.server.port: "5678"
      traefik.docker.network: "homelab"
