---
- name: Create pihole directory
  ansible.builtin.file:
    path: "{{ data_dir }}/pihole/pihole"
    state: directory
    mode: "0755"
    access_time: preserve
    modification_time: preserve

- name: Create pihole/dnsmasq.d directory
  ansible.builtin.file:
    path: "{{ data_dir }}/pihole/pihole/dnsmasq.d"
    state: directory
    mode: "0755"
    access_time: preserve
    modification_time: preserve

# We should write out our local dns entries to /etc/pihole/custom.list in the container
- name: Create custom.list dns entries
  ansible.builtin.template:
    src: custom.list.j2
    dest: "{{ data_dir }}/pihole/pihole/custom.list"
    mode: "0644"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create pihole container
  community.docker.docker_container:
    name: pihole
    image: cbcrowe/pihole-unbound:latest
    state: started
    restart_policy: unless-stopped
    networks_cli_compatible: yes
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{pihole_password}}"
    volumes:
      - "{{ docker_dir }}/pihole/config:/config"
      - "{{ data_dir }}/pihole/dnsmasq.d:/etc/dnsmasq.d"
      - "{{ data_dir }}/pihole/pihole/custom.list:/etc/pihole/custom.list"
    networks:
      - name: homelab
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853"
    capabilities:
      - NET_ADMIN
    labels:
      traefik.enable: "true"
      traefik.http.routers.pihole.entrypoints: "http"
      traefik.http.routers.pihole.rule: "Host(`pihole.{{ domain }}`)"
      traefik.http.middlewares.pihole-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.pihole.middlewares: "pihole-https-redirect"
      traefik.http.routers.pihole-secure.entrypoints: "https"
      traefik.http.routers.pihole-secure.rule: "Host(`pihole.{{ domain }}`)"
      traefik.http.routers.pihole-secure.tls: "true"
      traefik.http.routers.pihole-secure.service: "pihole"
      traefik.http.routers.pihole-secure.middlewares: "authelia@docker"
      traefik.http.services.pihole.loadbalancer.server.port: "80"
